CREATE TABLE `siteSettings` (
	`id` int NOT NULL,
	`siteName` varchar(120) NOT NULL,
	`siteTagline` varchar(180) NOT NULL,
	`logoUrl` text,
	`navHomeLabel` varchar(80) NOT NULL,
	`navArticlesLabel` varchar(80) NOT NULL,
	`navCategoriesLabel` varchar(80) NOT NULL,
	`navAboutLabel` varchar(80) NOT NULL,
	`navContactLabel` varchar(80) NOT NULL,
	`homeEyebrow` varchar(180) NOT NULL,
	`homeTitleMain` varchar(180) NOT NULL,
	`homeTitleAccent` varchar(180) NOT NULL,
	`homeTitleEnd` varchar(180) NOT NULL,
	`homeDescription` text NOT NULL,
	`homePrimaryCta` varchar(120) NOT NULL,
	`homeSecondaryCta` varchar(120) NOT NULL,
	`footerDescription` text NOT NULL,
	`footerKicker` varchar(180) NOT NULL,
	`newsletterTitle` varchar(120) NOT NULL,
	`newsletterDescription` text NOT NULL,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `siteSettings_id` PRIMARY KEY(`id`)
);
